### PR TITLE
nerves_system_br: bump to v1.29.1

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
@jjcarstens lol - you script approved this, didn't you? Check out the CI build error. I'm looking into it and hoping it's easy.

**Comment by jjcarstens** [comment]
Welp, I spot checked many of the other build failures which were just timing out and would just rerun. Of course this one I glaze over is an actual error 🤦🏼

**Comment by fhunleth** [comment]
Fixed now

**Comment by fhunleth** [comment]
Spoke too soon. It builds locally for me now so the NEON intrinsics error message is fixed. However, it still failed on CI.

**Pull request merged**
