### PR TITLE
add support for raspberry pi joystick

### PR DESCRIPTION
**Pull request by mmmries**
Based on a conversation with @fhunleth it looks like this will enable the driver so we can interact with the raspberry pi joystick. I'm still investigating the best way to interact with the joystick (using https://github.com/ConnorRigby/joystick/ or by just using `File.read`), but this change does make the device show up:

```
iex(blinky@blinky.local)24> ls "/sys/class/input/event1/device"
capabilities     event1           id               modalias         name
phys             power            properties       subsystem        uevent
uniq
iex(blinky@blinky.local)25> File.read "/sys/class/input/event1/device/properties"
{:ok, "0\n"}
iex(blinky@blinky.local)26> File.read "/sys/class/input/event1/device/modalias"
{:ok, "input:b0018v0000p0000e0000-e0,1,14,kramlsfw\n"}
iex(blinky@blinky.local)27> File.read "/sys/class/input/event1/device/name"
{:ok, "Raspberry Pi Sense HAT Joystick\n"}
iex(blinky@blinky.local)28> File.read "/sys/class/input/event1/device/uevent"
{:ok,
 "PRODUCT=18/0/0/0\nNAME=\"Raspberry Pi Sense HAT Joystick\"\nPHYS=\"rpi-sense-joy/input0\"\nPROP=0\nEV=100003\nKEY=1680 0 0 10000000\nMODALIAS=input:b0018v0000p0000e0000-e0,1,14,kramlsfw\n"}
```

The sense-hat is compatible with the pi3 b, pi2 b, and rpi a+ and b+. So I'm thinking we should open a similar PR for the https://github.com/nerves-project/nerves_system_rpi3, https://github.com/nerves-project/nerves_system_rpi2 and https://github.com/nerves-project/nerves_system_rpi

Screen Shot 2020-06-08 at 10 17 57 PM

### CODE REVIEW

**Comment by mmmries** [comment]
I could also just document this somewhere so that other people can customize their image when they want to use the raspberry pi joystick. Not sure how much this will affect the firmware size, but:

```
riespro:blinkier$ ls -al _build/rpi3a_dev/nerves/images/blinkier.fw
-rw-r--r--  1 michaelries  staff  31289498 Jun  8 22:12 _build/rpi3a_dev/nerves/images/blinkier.fw
```

**Comment by fhunleth** [comment]
This looks good to me. I have a Sense Hat that I've never used with Nerves and can give it a try too.

Also, `File.read` won't work since the inputs come through a special file that magically changes on updates. Erlang doesn't expect that to happen. My personal preference would be to try `input_event` since it's generic for all input devices. I realize that it is not being maintained at the moment, but it basically works and is being used by other libraries (like Scenic).

**Comment by mmmries** [comment]
I'll look into `input_event`, I think that should work great since the joystick driver is setup to emit the equivalent of keypresses for enter, and arrow keys.

Yeah

Should I open a similar PR for the other nerves system repo's to enable this by default for those other platforms that are supported by the sense hat?

**Comment by mmmries** [comment]
Just tried this out with `input_event` during my lunch break and the joystick shows up as an input. Pushing the buttons sends event messages just like I'd expect 🎉 ⚡ 💙 🖤 💛 💚 ❤️ 

Screen Shot 2020-06-09 at 1 52 00 PM

**Comment by fhunleth** [comment]
Thanks for the simple PR and the screenshot of it working! That makes it so easy to review!

We're planning on making official Nerves systems soon so that we can get OTP 23 support out for Nerves users. As you mentioned earlier, this should go in the other official Raspberry Pi systems for consistency. If you have anything ready to go for other boards, please send a PR. No worries if not. Justin or I will replicate the patch across the other repos.

**Comment by mmmries** [comment]
YAY! I've contributed something to a core part of Nerves!!!! Thanks for all the guidance on this. I'll try to replicate the process of changing at least one of the other systems and compare the defconfig diff to what we did here.

**Pull request merged**
